apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvcapp
  namespace: mvc
spec:
  selector:
    matchLabels:
      app: mvcapp
  replicas: 3
  template:
    metadata:
      labels:
        app: mvcapp
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: agentpool
                operator: In
                values:
                - mainnp
      containers:
      - name: mvcapp
        image: seanmckdemo.azurecr.io/mvc-hpa:0.3
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
        - name: metrics
          containerPort: 9000
