apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mvc-monitor
  namespace: prom
  labels:
    app: mvc-monitor    
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mvcapp
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  namespaceSelector:
    matchNames:
    - mvc